[package]
name = "rust-aes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.2"
clap = { version = "4.3.9", features = ["cargo"] }
